name: Sync rss feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: "28 0,8,16 * * *"
  workflow_dispatch:

jobs:
  sync-rss:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: news
          path: branch-news
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          path: branch-main

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Run rssync and commit feeds
        id: commit
        run: |
          cp -f branch-main/rssync-config.json branch-news
          cd branch-news
          uvx --from git+https://github.com/WaferJay/rssync rssync

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update news"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: news
          directory: branch-news
